FROM amazoncorretto:17 AS runner

WORKDIR /auth

EXPOSE 8080

COPY --from=aida0/gitfolio_builder:test /gitfolio_back/build/.env .env
COPY --from=aida0/gitfolio_builder:test /gitfolio_back/build/*-auth-*-SNAPSHOT.jar auth.jar

CMD [ "java", "-jar", "auth.jar" ]