apiVersion: v1
kind: Service
metadata:
  name: mongo-member-service  # Secret에 정의된 MEMBER_MONGO_DB_HOST와 일치
  namespace: default
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-resume-service  # Secret에 정의된 RESUME_MONGO_DB_HOST와 일치
  namespace: default
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-chat-service    # Secret에 정의된 CHAT_MONGO_DB_HOST와 일치
  namespace: default
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb