apiVersion: v1
kind: Service
metadata:
  name: redis-auth-service    # ConfigMap에 정의된 AUTH_REDIS_HOST와 일치
  namespace: default
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis-resume-service  # ConfigMap에 정의된 RESUME_REDIS_HOST와 일치
  namespace: default
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis