apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment  # 배포 이름으로 notification-deployment 사용
  labels:
    app: notification           # notification 서비스임을 나타내는 레이블
spec:
  replicas: 2                   # 고가용성을 위한 2개의 복제본
  selector:
    matchLabels:
      app: notification         # notification 레이블을 가진 파드 선택
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: aida0/gitfolio_notification:test  # Docker Hub의 notification 서비스 이미지
          ports:
            - containerPort: 8080                    # 애플리케이션의 포트
          envFrom:
            - configMapRef:
                name: backend-configmap              # 일반 설정값들을 가진 ConfigMap 참조
            - secretRef:
                name: backend-secret                 # 민감한 정보를 가진 Secret 참조
          resources:                               # 컨테이너 리소스 제한 설정
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"