# backend/deployments/auth-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  template:
    spec:
      containers:
        - name: auth
          envFrom:
            - configMapRef:
                name: backend-configmap    # 변경된 이름으로 참조
            - secretRef:
                name: backend-secret      # 변경된 이름으로 참조