services:
  auth:
    platform: linux/amd64
    image: aida0/gitfolio_auth:test
    container_name: gitfolio_auth
    ports:
      - target: 8080
        published: 80
        protocol: tcp
      - target: 8080
        published: 443
        protocol: tcp
      - target: 8080
        published: 5000
        protocol: tcp
    networks:
      - back
      
  member:
    platform: linux/amd64
    image: aida0/gitfolio_member:test
    container_name: gitfolio_member
    ports:
      - target: 8080
        published: 81
        protocol: tcp
      - target: 8080
        published: 444
        protocol: tcp
      - target: 8080
        published: 5000
        protocol: tcp
    networks:
      - back
      
  networks:
    back:
      driver: overlay
      attachable: true