services:
  ai:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    image: aida0/gitfolio_ai:test
    container_name: gitfolio_ai
    ports:
      - target: 8000
        published: 80
        protocol: tcp
      - target: 8000
        published: 443
        protocol: tcp
      - target: 8000
        published: 5000
        protocol: tcp