# auth-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth
spec:
  type: ClusterIP
  ports:
    - port: 8080          # AUTH_SERVER_PORT=8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: auth