# chat-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: default
  labels:
    app: chat
spec:
  type: ClusterIP
  ports:
    - port: 8080          # CHAT_SERVER_PORT=8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: chat