# member-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: default
  labels:
    app: member
spec:
  type: ClusterIP
  ports:
    - port: 8080          # MEMBER_SERVER_PORT=8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9090          # MEMBER_GRPC_PORT=9090
      targetPort: 9090
      protocol: TCP
      name: grpc
  selector:
    app: member