# notification-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: default
  labels:
    app: notification
spec:
  type: ClusterIP
  ports:
    - port: 8080          # NOTIFICATION_SERVER_PORT=8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: notification