# payment-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: default
  labels:
    app: payment
spec:
  type: ClusterIP
  ports:
    - port: 8080          # PAYMENT_SERVER_PORT=8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: payment