# resume-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: resume-service
  namespace: default
  labels:
    app: resume
spec:
  type: ClusterIP
  ports:
    - port: 8080          # RESUME_SERVER_PORT=8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: resume
# resume-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: resume-service
  namespace: default
  labels:
    app: resume
spec:
  type: ClusterIP
  ports:
    - port: 8080          # RESUME_SERVER_PORT=8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: resume