services:
  frontend:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: dockerfile
    image: aida0/gitfolio_front:test
    ports:
      - target: 3000
        published: 80
        protocol: tcp
      - target: 3000
        published: 443
        protocol: tcp