services:
  frontend:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    image: aida0/gitfolio_front:test
    container_name: gitfolio_front
    ports:
      - target: 3000
        published: 80
        protocol: tcp
      - target: 3000
        published: 443
        protocol: tcp
      - target: 3000
        published: 5000
        protocol: tcp