services:
  sentry_bot:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    image: aida0/sixmen_discord_bot:latest
    container_name: discord_bot
    env_file: .env
    ports:
      - target: 80
        published: 81
        protocol: tcp
      - target: 443
        published: 444
        protocol: tcp