# backend-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  # 서비스 URL 설정
  REDIRECT_ONBOARDING_URL: "https://www.gitfolio.site/onboarding"
  REDIRECT_MAIN_URL: "https://www.gitfolio.site/community"

  # 서비스 포트 설정
  MEMBER_GRPC_PORT: "9090"
  AUTH_SERVER_PORT: "8080"
  MEMBER_SERVER_PORT: "8080"
  RESUME_SERVER_PORT: "8080"
  PAYMENT_SERVER_PORT: "8080"
  NOTIFICATION_SERVER_PORT: "8080"
  CHAT_SERVER_PORT: "8080"

  # Kafka 설정
  KAFKA_HOST1: "kafka1-service:9092"

  # Redis 호스트 설정
  AUTH_REDIS_HOST: "redis-auth-service"
  RESUME_REDIS_HOST: "redis-resume-service"

  # Redis 포트 설정
  AUTH_REDIS_PORT: "6379"
  RESUME_REDIS_PORT: "6379"