- hosts: mongo
  gather_facts: no
  tasks:
  - name: Write docker-compose.yaml
    copy:
      dest: "{{ ansible_home_dir }}/docker-compose.yaml"
      content: |
        services:
          mongo:
            image: mongo:5.0
            container_name: gitfolio-mongo
            ports:
              - target: 27017
                published: 27017
                protocol: tcp
            environment:
              MONGO_INITDB_DATABASE: gitfolio_mongo
            networks:
              - back
        
        networks:
          back:
            driver: overlay
            attachable: true

  - name: Initialize Docker Swarm
    shell: docker swarm init
    ignore_errors: yes
    
  - name: Start docker-compose.yaml
    shell: docker-compose up -d
    args:
      chdir: "{{ ansible_home_dir }}"