- hosts: all
  tasks:
  - name: Install environment
    dnf:
      name:
        - docker
        - pip
      state: latest

  - name: Change Docker group
    shell: |
      newgrp docker
      sudo usermod -aG docker ec2-user

  - name: Start Docker
    systemd:
      name: docker
      state: started

  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: '0755'
      force: yes

  - name: Install docker-compose
    shell: chmod +x /usr/local/bin/docker-compose
  
  - name: Restart Docker
    systemd:
      name: docker
      state: restarted
      enabled: yes