- hosts: back1
  gather_facts: no
  tasks:
  - name: down containers
    shell: docker-compose down -v
    args:
      chdir: "{{ ansible_home_dir }}"

  # - name: pull containers
  #   shell: docker-compose pull
  #   args:
  #     chdir: "{{ ansible_home_dir }}"

  # - name: Write docker-compose.yaml
  #   template:
  #     src: docker-compose.yaml.j2
  #     dest: "{{ ansible_home_dir }}/docker-compose.yaml"

  - name: up containers
    shell: docker-compose up -d
    args:
      chdir: "{{ ansible_home_dir }}"
      
  - name: Execute docker ps using shell
    shell: docker ps -a
    register: docker_ps_output

  - name: Display shell command output
    debug:
      var: docker_ps_output.stdout_lines