- name: Configure Kubernetes prerequisites
  hosts: kubernetes
  tasks:
    - name: Update system
      dnf:
        name: '*'
        state: latest
  
    - name: Install dependencies
      dnf:
        name:
          - dnf-plugin-versionlock
          - curl
          - iproute-tc
          - ca-certificates
          - pip
          - containerd
        state: present

    # - name: Disable swap
    #   shell: |
    #     swapoff -a
    #   changed_when: false

    - name: Configure Kubernetes prerequisites
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Configure sysctl parameters
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        sysctl_file: /etc/sysctl.d/k8s.conf
        reload: yes
      loop:
        - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
        - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
        - { name: 'net.ipv4.ip_forward', value: '1' }

    - name: Create containerd directory
      file:
        path: /etc/containerd
        state: directory
        owner: root
        group: root
        mode: '0750'

    - name: Save containerd settings to file
      shell: |
        containerd config default | tee /etc/containerd/config.toml > /dev/null

    - name: Replace SystemdCgroup with SystemCgroup
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^SystemdCgroup = false'
        line: 'SystemCgroup = true'
        state: present

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Get containerd status 
      shell: systemctl status containerd
      register: countainerd_status

    - name: Display containerd status
      debug:
        var: countainerd_status.stdout_lines

    - name: Add Kubernetes repo
      yum_repository:
        name: kubernetes
        description: Kubernetes repo
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        gpgkey: 
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes
        enabled: yes
        exclude: kubelet kubeadm kubectl

    - name: Update system
      dnf:
        name: '*'
        state: latest

    - name: Install Kubernetes packages
      dnf:
        name:
          - kubelet-{{ ansible_kubernetes_version }}-0
          - kubeadm-{{ ansible_kubernetes_version }}-0
          - kubectl-{{ ansible_kubernetes_version }}-0
        state: present
        disable_excludes: kubernetes

    - name: Hold Kubernetes packages version
      community.general.dnf_versionlock:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        
    - name: Start and enable kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Get Kubernetes packages status
      shell: |
        kuberlet --version
        kubeadm version
        kubectl version --output=yaml
      register: kube_packages_status

    - name: Display containerd status
      debug:
        var: kube_packages_status.stdout_lines