- name: Configure Kubernetes master node
  hosts: master
  tasks:
    - name: Update kubeadm images
      shell: |
        kubeadm config images pull --cri-socket /run/containerd/containerd.sock

    - name: Initialize Kubernetes cluster
      shell: |
        kubeadm init --apiserver-advertise-address={{ ansible_master_host }} --pod-network-cidr={{ ansible_pod_network_cidr }} --cri-socket /run/containerd/containerd.sock --ignore-prefilght-errors=NumCPU
      args:
        creates: /etc/kubernetes/admin.conf
    
    - name: Create .kube directory
      file:
        path: "{{ ansible_home_dir }}/.kube"
        state: directory
        mode: '0755'

    - name: Copy admin.conf to root's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_home_dir }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
    
    - name: Install Calico network plugin
      shell: |
        kubectl create -f {{ ansible_calico_manifest_link }}/tigera-operator.yaml
        kubectl create -f {{ ansible_calico_manifest_link }}/custom-resources.yaml
    
    - name: Get calico-system pods status
      shell: |
        watch kubectl get pods -n calico-system
      register: calico_system_pods_status

    - name: Display calico-system pods
      debug:
        var: calico_system_pods_status.stdout_lines