- name: Configure Kubernetes master node
  hosts: master
  tasks:
    - name: Update system
      dnf:
        name: '*'
        state: latest
  
    - name: Install dependencies
      dnf:
        name:
          - curl
          - iproute-tc
          - pip
          - containerd
        state: present

    - name: Configure containerd prerequisites
      shell: |
        cat << EOF | tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF
        modprobe overlay
        modprobe br_netfilter

    - name: Configure kernel parameters for Kubernetes
      shell: |
        cat << EOF | tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward = 1
        sysctl --system

    - name: Create containerd directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Install containerd
      shell: |
        containerd config default | tee /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemCgroup = true/g' /etc/containerd/config.toml

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Add Kubernetes repo
      shell: |
        cat << EOF | tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-e17-\$basearch
        enabled=1
        gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude=kubelet kubeadm kubectl
        EOF

    - name: Install Kubernetes packages
      dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        disable_excludes: kubernetes

    - name: Use kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started


    - name: Initialize Kubernetes cluster
      shell: |
        kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-prefilght-errors=NumCPU
      args:
        creates: /etc/kubernetes/admin.conf
    
    - name: Create .kube directory
      file:
        path: /root/.kube
        state: directory
        mode: '0755'

    - name: Coopy admin.conf to root's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
        group: root
        mode: '0600'
    
    - name: Install Calico network plugin
      shell: kubectl apply =-f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        creates: /etc/cni/net.d/calico-kubeconfig

    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: Store join command
      set_fact:
        join_command: "{{ join_command.stdout }}"