- name: Configure Kubernetes worker node
  hosts: master
  tasks:
    - name: Update system
      dnf:
        name: '*'
        state: latest
  
    - name: Install dependencies
      dnf:
        name:
          - curl
          - iproute-tc
          - pip
          - containerd
        state: present

    - name: Configure containerd prerequisites
      shell: |
        cat << EOF | tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF
        modprobe overlay
        modprobe br_netfilter

    - name: Configure kernel parameters for Kubernetes
      shell: |
        cat << EOF | tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward = 1
        sysctl --system

    - name: Create containerd directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Install containerd
      shell: |
        containerd config default | tee /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemCgroup = true/g' /etc/containerd/config.toml

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Add Kubernetes repo
      shell: |
        cat << EOF | tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-e17-\$basearch
        enabled=1
        gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude=kubelet kubeadm kubectl
        EOF

    - name: Install Kubernetes packages
      dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        disable_excludes: kubernetes

    - name: Use kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Join cluster
      shell: "{{ hostvars[groups['master'][0]]['join_command'] }}"
      args:
        creates: /etc/kubernetes/kubelet.conf