- name: Configure Kubernetes worker node
  hosts: worker
  become: true
  tasks:
    - name: Get join command from master
      shell: |
        kubeadm token create --print-join-command
      register: join_command
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true

    - name: Join cluster
      shell: >-
        {{ join_command.stdout | replace('"', '') | trim }}
      register: join_result
      failed_when: 
        - join_result.rc != 0 
        - "'node joined the cluster' not in join_result.stderr"
      args:
        creates: /etc/kubernetes/kubelet.conf